=== benkedda-louai/univ_tp/exo4.dtd
<!ELEMENT entete (titre,date,auteur+,motscle*,resume? )>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT auteur (#PCDATA)>
<!ELEMENT motscle (#PCDATA)>
<!ELEMENT resume (paragraph+)>
<!ELEMENT paragraph (#PCDATA)>

=== benkedda-louai/univ_tp/s_1/exercice4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE entete SYSTEM "exo4.dtd">
<entete>
    <titre>Title</titre>
    <date>2024-02-02</date>
    <auteur>louai</auteur>
    <auteur>benkedda</auteur>
    <motscle>XML</motscle>
    <motscle>DTD</motscle>
    <resume>
        <paragraph>lorem</paragraph>
        <paragraph>test</paragraph>
    </resume>
</entete>
