=== benkedda-louai/univ_tp/s_1/exercice6.dtd
<!ELEMENT cv (étatcivil, formation+,expérience*)>
<!ELEMENT étatcivil (nom, prénom, âge, lieu)>
<!ELEMENT formation (titre, date, mention?, description?)>
<!ELEMENT expérience (libellé, fonction?, année, observation?)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT prénom (#PCDATA)>
<!ELEMENT âge (#PCDATA)>
<!ELEMENT lieu (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT année (#PCDATA)>
<!ELEMENT titre (#PCDATA)>
<!ELEMENT libellé (#PCDATA)>
<!ELEMENT mention (#PCDATA)>
<!ELEMENT fonction (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT observation (#PCDATA)>

=== benkedda-louai/univ_tp/exo6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "exercice6.dtd">
<cv>
    <étatcivil>
        <nom>benkedda</nom>
        <prénom>louai</prénom>
        <âge>20</âge>
        <lieu>Touggourt</lieu>
    </étatcivil>
    <formation>
        <titre>Bachalor en Informatique</titre>
        <date>2024</date>
        <mention>Mention Très Bien</mention>
        <description>Université Kasdi Merbah Ouargla</description>
    </formation>
    <formation>
        <titre>Licence en Sciences</titre>
        <date>2018</date>
        <description>Université ABC</description>
    </formation>
    <expérience>
        <libellé>Développeur Web</libellé>
        <fonction>Analyste Programmeur</fonction>
        <année>2022-2023</année>
        <observation>Travail sur des projets de développement web.</observation>
    </expérience>
</cv>
