=== benkedda-louai/univ_tp/s_1/exercice5.dtd
<!ELEMENT messages (message+)>
<!ELEMENT message (dest+, contenu)>
<!ELEMENT dest (#PCDATA)>
<!ELEMENT contenu (#PCDATA)>
<!ATTLIST message 
    numero CDATA #REQUIRED
    date CDATA #IMPLIED
>
<!ATTLIST dest 
    bcc (oui | non) #IMPLIED
>

=== benkedda-louai/univ_tp/s_1/exo5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messages SYSTEM "exercice5.dtd">
<messages>
<message numero="1" date="2021-01-01">
<dest>promo2021</dest>
<dest bcc="oui">Pierre Nerzic</dest>
<contenu>Bonne année !</contenu>
</message>
<message numero="2">
<dest>promo2021</dest>
<contenu>Bonne rentrée !</contenu>
</message>
</messages>
